name: Release

# on:
#   push:
#     tags:
#       - 'v*'

# this will build for window/mac/linux on x86_64 and linux on aarch64/armhf
# TODO: work out tpoechtrager/osxcross to build aarch64 for OSX (on linux)
# TODO: pre-build docker containers for linux aarch64/armhf and mac aarch64
# TODO: look into docker buildx build --platform=linux/amd64,linux/arm64,linux/armhf .

on:
  push

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: windows x86_64
        run: |
          mkdir -p build-windows-x86_64
          cd build-windows-x86_64
          cmake .. -G "MinGW Makefiles"
          make

  mac:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: mac x86_64
        run: |
          mkdir -p build-mac-x86_64
          cd build-mac-x86_64/
          cmake ..
          make
      
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-aarch6 qemu-arm binfmt-misc
      - name: linux x86_64
        run: |
          sudo apt-get install -y xorg-dev libglu1-mesa-dev
          mkdir -p build-linux-x86_64
          cd build-linux-x86_64/
          cmake ..
          make
      - name: linux aarch64
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:latest
          options: -v ${{ github.workspace }}:/workdir -w /workdir --platform linux/aarch64
          run: |
            apt-get update && apt-get install -y xorg-dev libglu1-mesa-dev cmake git g++
            mkdir -p build-linux-aarch64
            cd build-linux-aarch64/
            cmake ..
            make
      - name: linux armhf
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:latest
          options: -v ${{ github.workspace }}:/workdir -w /workdir --platform linux/armhf
          run: |
            apt-get update && apt-get install -y xorg-dev libglu1-mesa-dev cmake git g++
            mkdir -p build-linux-armhf
            cd build-linux-armhf/
            cmake ..
            make
  

