name: Release

on:
  push:
    tags:
      - 'v*'

# this will build for window/linux on x86_64 and linux on aarch64/armhf and mac universal (x86_64/arm64)
# TODO: pre-build docker containers for linux aarch64/armhf and mac aarch64


jobs:
  create_release:
    runs-on: ubuntu
    needs: [windows, mac, linux]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: create_release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            my_raylib_game-windows.zip
            my_raylib_game-mac.zip
            my_raylib_game-linux-x86_64.zip
            my_raylib_game-linux-aarch64.zip
            my_raylib_game-linux-armhf.zip
          
  
  windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: windows x86_64
        run: |
          mkdir -p build-windows-x86_64
          cd build-windows-x86_64
          cmake .. -G "MinGW Makefiles"
          make
          zip ../my_raylib_game-windows.zip my_raylib_game.exe

  mac:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: mac universal
        run: |
          mkdir -p build-mac-universal
          cd build-mac-universal/
          export CMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          cmake ..
          make
          zip ../my_raylib_game-mac.zip my_raylib_game
      
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu qemu-system-misc qemu-user-static qemu-user binfmt-support
      - name: linux x86_64
        run: |
          sudo apt-get install -y xorg-dev libglu1-mesa-dev
          mkdir -p build-linux-x86_64
          cd build-linux-x86_64/
          cmake ..
          make
          zip ../my_raylib_game-linux-x86_64.zip my_raylib_game
      - name: linux aarch64
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:latest
          options: -v ${{ github.workspace }}:/workdir -w /workdir --platform linux/aarch64
          run: |
            apt-get update && apt-get install -y xorg-dev libglu1-mesa-dev cmake git g++
            mkdir -p build-linux-aarch64
            cd build-linux-aarch64/
            cmake ..
            make
            zip ../my_raylib_game-linux-aarch64.zip my_raylib_game
      - name: linux armhf
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:latest
          options: -v ${{ github.workspace }}:/workdir -w /workdir --platform linux/armhf
          run: |
            apt-get update && apt-get install -y xorg-dev libglu1-mesa-dev cmake git g++
            mkdir -p build-linux-armhf
            cd build-linux-armhf/
            cmake ..
            make
            zip ../my_raylib_game-linux-armhf.zip my_raylib_game
  

